# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
   - index.md
   - talks.md
   - images.liquid

footer: '<a href="http://phrack.org">phrack.org</a> | <a href="https://www.h2hc.com.br/h2hc/pt/evento">H2HC</a> | <a href="https://nullbyte-con.org/">NullByte</a> | <a href="https://www.x33fcon.com/#!about.md">x33fcon</a> | <a href="https://defcon.org/html/links/dc-faq/dc-faq.html">DEFCON</a>'

style: hacker # dark (default) or light
# listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
